#!/bin/sh

##
#	gitpk package
#
#	Version
#	1.0.0
#	20141212
##

#	Variables
LPATH=/Users/marius/Development/MacPorts/ports/
GPATH=/opt/local/var/macports/sources/rsync.macports.org/release/tarballs/ports/

PKG=$(port file $1|sed "s|$LPATH||"|sed "s|$GPATH||"|sed 's/Portfile//')

cd $LPATH

/opt/local/bin/git add $PKG/Portfile

if [ -d "$PKG/files" ]; then
	/opt/local/bin/git add $PKG/files/*
fi
