#!/bin/sh

##
#	NAME
#	mkorig
#
#	SYNOPSIS
#	mkorig path
#
#	DESCRIPTION
#	skorig makes a backup copy of a file for building patch files
#
#	VERSION
#	1.0.0
#	20150110
##

echo "cp -p $1 $1.orig"
cp -p $1 $1.orig
