#!/bin/sh

##
#	mpcheck [-a|-e|-f|-m|-o|-s|-y]
#	2.1.0
#	20150102
##

EVERYTHING=FALSE
FILE=FALSE
MY=FALSE
OCTAVE=FALSE
SERVER=FALSE
SECURITY=FALSE

while getopts afmosy o
	do case $o in
		a)	MY="TRUE"
			SERVER="TRUE"
			SECURITY="TRUE";;
		e)	EVERYTHING="TRUE";;
		f) FILE="TRUE";;
		m) MY="TRUE";;
		o) OCTAVE="TRUE";;
		s) SERVER="TRUE";;
		y) SECURITY="TRUE";;
	esac
done
shift `echo $OPTIND-1 | bc`

if [ $EVERYTHING == "TRUE" ]; then
	echo "All installed"
	pkgs=$(port installed | gawk '{print $1}' | uniq)
fi
if [ $FILE == "TRUE" ]; then
	echo "Saving all installed to file"
	cd /Users/marius/Development/MacPorts/var
	pkgs=$(port installed | gawk '{print $1}' | uniq)
	for pkg in $pkgs
	do
		port livecheck $pkg >> mpcheck.$(date "+%Y%m%d") 2>&1
	done
	livediff > mpdiff.$(date "+%Y%m%d")
fi
if [ $MY == "TRUE" ]; then
	echo "Maintained ports"
	pkgs="dnscrypt-proxy duff ffe freefont-ttf gawk gifsicle GiNaC gnutls grep grsync \
	gsed hatools iftop LaTeXiT lftp libgcrypt libgpg-error libpcap libtasn1 \
	littleutils mksh pyxplot retail rr stunnel surblhost ts wcd"
fi
if [ $OCTAVE == "TRUE" ]; then
	echo "octave etc."
	pkgs="$pkgs octave octave-bim octave-communications octave-control octave-divand \
	octave-fem-fenics octave-fits octave-fl-core octave-fpl \
	octave-fuzzy-logic-toolkit octave-general octave-geometry octave-image octave-io \
	octave-linear-algebra octave-mechanics octave-miscellaneous octave-msh octave-mvn \
	octave-nan octave-ncarray octave-netcdf octave-octcdf octave-octproj octave-optics \
	octave-optim octave-quaternion octave-parallel octave-quaternion \
	octave-queueing octave-signal octave-specfun octave-splines octave-struct \
	octave-stk octave-tsa py27-fiat"
fi
if [ $SERVER == "TRUE" ]; then
	echo "Server packages"
	pkgs="$pkgs apache24-devel apr apr-util bind9 clamav gitlist mailman mysql56 \
	ntp openssh openssl php56 squirrelmail sqlite3"
fi
if [ $SECURITY == "TRUE" ]; then
	echo "Security packages"
	pkgs="$pkgs daq nagios nmap ntop snort wireshark"
fi

if [ $FILE == "FALSE" ]; then
	for pkg in $pkgs
	do
		echo "port livecheck $pkg"
		port livecheck $pkg
	done
fi