#!/bin/sh

##
#	mpcheck [-a|-e|-f|-m|-o|-s|-y]
#	2.3.1
#	20150128
##

DEVELOPMENT="FALSE"
EVERYTHING="FALSE"
FILE="FALSE"
MY="FALSE"
OCTAVE="FALSE"
SERVER="FALSE"
SECURITY="FALSE"

while getopts adefmosy o
	do case $o in
		a)	MY="TRUE"
			SERVER="TRUE"
			SECURITY="TRUE";;
		d)	DEVELOPMENT="TRUE";;
		e)	EVERYTHING="TRUE";;
		f)	EVERYTHING="TRUE"
			FILE="TRUE";;
		m)	MY="TRUE";;
		o)	OCTAVE="TRUE";;
		s)	SERVER="TRUE";;
		y)	SECURITY="TRUE";;
	esac
done
shift `echo $OPTIND-1 | bc`

#	Get package list
if [ $DEVELOPMENT == "TRUE" ]; then
	echo "Development packages"
	pkgs="autoconf automake cmake"
fi
if [ $EVERYTHING == "TRUE" ]; then
	echo "All installed"
	pkgs=$(port installed | gawk '{print $1}' | uniq)
fi
if [ $MY == "TRUE" ]; then
	echo "Maintained ports"
	pkgs="$pkgs dnscrypt-proxy duff ffe freefont-ttf gawk gifsicle GiNaC gnutls grep grsync \
	gsed hatools iftop LaTeXiT lftp libgcrypt libgpg-error libpcap libtasn1 \
	littleutils mksh pyxplot retail rr stunnel surblhost ts wcd"
fi
if [ $OCTAVE == "TRUE" ]; then
	echo "Octave, et al."
	pkgs="$pkgs octave octave-bim octave-communications octave-control octave-divand \
	octave-fem-fenics octave-fits octave-fl-core octave-fpl \
	octave-fuzzy-logic-toolkit octave-general octave-geometry octave-image octave-io \
	octave-linear-algebra octave-mechanics octave-miscellaneous octave-msh octave-mvn \
	octave-nan octave-ncarray octave-netcdf octave-octcdf octave-octproj octave-optics \
	octave-optim octave-quaternion octave-parallel octave-quaternion \
	octave-queueing octave-signal octave-specfun octave-splines octave-struct \
	octave-stk octave-tsa py27-fiat"
fi
if [ $SERVER == "TRUE" ]; then
	echo "Server packages"
	pkgs="$pkgs adns apache24-devel apr apr-util bind9 clamav gitlist mailman mysql56 \
	ntp openssh openssl php56 squirrelmail sqlite3"
fi
if [ $SECURITY == "TRUE" ]; then
	echo "Security packages"
	pkgs="$pkgs daq nagios nmap ntop snort wireshark"
fi

#	Output
if [ $FILE == "TRUE" ]; then
	echo "Saving to file"
	cd /Users/marius/Development/MacPorts/var
	for pkg in $pkgs
	do
		port livecheck $pkg >> mpcheck.$(date "+%Y%m%d") 2>&1
	done
	livediff > mpdiff.$(date "+%Y%m%d")
else
	spkgs=$(echo $pkgs | tr " " "\n" | sort)
	for pkg in $spkgs
	do
		echo "port livecheck $pkg"
		port livecheck $pkg
	done
fi
