#!/bin/sh

##
#	mpdiff package
#
#	Generate MacPorts patch for Portfile
#
#	1.2.0
#	20141127
##

#	Variables
LPATH=/Users/marius/Development/MacPorts/ports/
GPATH=/opt/local/var/macports/sources/rsync.macports.org/release/tarballs/ports/

PKG=$(port file $1|sed "s|$LPATH||"|sed "s|$GPATH||"|sed 's/Portfile//')

#	Go to directory
cd $LPATH/$PKG

#	Perform diff
if [ -e Portfile.orig ]; then
	echo "diff -u Portfile.orig Portfile > Portfile-$1.diff"
	diff -u Portfile.orig Portfile > Portfile-$1.diff
fi
