#!/bin/sh

##
#	mpportf package
#
#	Copy Portfile to local tree
#
#	1.2.0
#	20140124
##

#	Variables
LPATH=/Users/marius/Development/MacPorts/ports/
GPATH=/opt/local/var/macports/sources/rsync.macports.org/release/tarballs/ports/

PKG=$(port file $1|sed "s|$LPATH||"|sed "s|$GPATH||"|sed 's/Portfile//')

#	Get copy
cd $LPATH

#	Make directory if id doesn't exist
if [ ! -e $PKG ]; then
	mkdir -p $PKG
fi

#	Copy Portfile
cd $LPATH/$PKG
cp $GPATH/$PKG/Portfile Portfile.orig

cp Portfile.orig Portfile

#	Copy files directory
if [ -e files ]; then
	mkdir files
fi
cp -R $GPATH/$PKG/files/ files/

#	Update portindex
cd $LPATH
portindex
