#!/bin/sh

##
#	mptidy package
#
#	Version
#	1.1.0
#	20150109
##

PKX=$(port installed $1|awk '{l[NR] = $2} END {for (i=2; i<=NR-2; i++) print l[i]}')

for PKG in $PKX
do
	echo "sudo port uninstall $1 $PKG"
	sudo port uninstall $1 $PKG
done
