#!/bin/sh

##
#	mpup [-u]
#
#	1.4.0
#	20150121
##

# get options
OPT=""
while getopts u o
	do case $o in
		u)	OPT="-u";;
	esac
done
shift `echo $OPTIND-1 | bc`


# timestamp
echo Start $(date)
cd /Users/marius/Development/MacPorts/ports

# get latest from MacPorts
sudo /opt/local/bin/port sync

# get latest from git (if there is a local tree)
ISGIT=$(git rev-parse --is-inside-work-tree)
if [ "$ISGIT" == "true" ]; then
    su marius -c "/opt/local/bin/git pull origin master"
    cp group/*.tcl /opt/local/var/macports/sources/rsync.macports.org/release/tarballs/ports/_resources/port1.0/group/
    portindex
fi

# update
sudo /opt/local/bin/port $OPT upgrade outdated

# timestamp
echo Finish $(date)
