#!/bin/sh

##
#	NAME
#	msorig
#
#	SYNOPSIS
#	msorig package path
#
#	DESCRIPTION
#	skorig makes a backup copy of a file for building patch files
#
#	VERSION
#	1.0.0
#	20141207
##

#	Variables
LPATH=/Users/marius/Development/MacPorts/ports/
GPATH=/opt/local/var/macports/sources/rsync.macports.org/release/tarballs/ports/
PKG=$(port file $1|sed "s|$LPATH||"|sed "s|$GPATH||"|sed 's/Portfile//')
VERS=$(port info --version $1 | awk '{print $2}')

#	Go to directory
cd $LPATH/$PKG/work/$1-$VERS

#	Create backup
echo "cp -p $2 $2.orig"
cp -p $2 $2.orig
